version: '3.1'
services:
  anki-db:
    image: postgres:14-alpine
    container_name: server-database
    ports:
      - "6541:5432"
    environment:
    - POSTGRES_DB=server_anki_db
    - POSTGRES_USER=root
    - PGDATA=/var/lib/postgresql/data1
    - POSTGRES_PASSWORD=root
    - DB_HOST=localhost
    - DB_PORT=5432

  bot-db:
    image: postgres:14-alpine
    container_name: bot-database
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=bot_anki_db
      - POSTGRES_USER=root1
      - PGDATA=/var/lib/postgresql/data1
      - POSTGRES_PASSWORD=root1
      - DB_HOST=localhost
      - DB_PORT=5432