version: '3.1'
services:
  anki-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
    - POSTGRES_DB=stat_db
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - DB_HOST=localhost
    - DB_PORT=5432
